### ISSUE TITLE
Specified cast is not valid while using as WinRT server on net8.0

### ISSUE THREAD

**Issue by hez2010** [shmuelie/Shmuelie.WinRTServer#19]
Hello, thanks for the project.

I'm trying to use it to create a WinRT server with CsWinRT to run on net8.0, and here is the project I'm using for testing: https://github.com/hez2010/WinRTServerTest

I copy-pasted your library code because in net8.0 the `IActivationFactory` interface type will fail to load, so I removed the `: IActivationFactory` from `BaseActivationFactory`.

The `ActivationFactory` can be created successfully, but when activating the class `TestClass`, it failed to cast the managed object (an instance of `TestClass`) to `IInspectable` at `unkwnPtr.CopyTo(instance)` in `BaseActivationFactoryProxy.ActivateInstance` with `Specified cast is not valid.`.

https://github.com/shmuelie/Shmuelie.WinRTServer/blob/8bfa82efb26cdc70d98288134aa71c1d5465665d/src/Shmuelie.WinRTServer/Internal/BaseActivationFactoryProxy.cs#L233

<img width="451" alt="image" src="https://github.com/shmuelie/Shmuelie.WinRTServer/assets/14960345/134e803e-f7b4-47c6-88c4-52d7ae7c6fff">

**Comment by shmuelie** [comment]
Yeah, the server components highly rely on the built in COM/WinRT marshaling. I've started working on support for "modern" .NET code but it's not working yet.

**Comment by shmuelie** [comment]
I got the COM Server working on modern .NET. Working on WinRT server now

**Comment by shmuelie** [comment]
Ok, @hez2010 try using https://github.com/shmuelie/Shmuelie.WinRTServer/pkgs/nuget/Shmuelie.WinRTServer/158852442 and if that works, I'll prepare a full release for nuget.org

**Comment by hez2010** [comment]
Hello, thanks for the investment into modern .net support for WinRT. 

I tested it with a simple test project https://github.com/hez2010/WinRTServerTest but unfortunately it still failed with `Interface was not supported`.
However, this time the instance on the server can be activated successfully, but soon it failed at `VftblIUnknown.QueryInterface(ThisPtr, &iid, &thisPtr);` in `WinRT.IObjectReference` on the client side.

Is there anything I'm missing in the test project?

**Comment by hez2010** [comment]
I suspect this is an issue from CsWinRT as I hit the same exception while using `RoRegisterActivationFactories` manually. 
Opened an issue there: https://github.com/microsoft/CsWinRT/issues/1419

**Comment by shmuelie** [comment]
Ok, I looked at your test project and you're missing the Metadata and interface projects that my sample shows. I admit having them is a pain but I haven't been able to get away from them yet

**Comment by hez2010** [comment]
I see. I just added the interface and metadata projects but still with no luck.
You may see the simple test project here: https://github.com/hez2010/WinRTServerTest/tree/metadata

**Comment by shmuelie** [comment]
The `TestClass` type needs to have a `GuidAttribute` like https://github.com/shmuelie/Shmuelie.WinRTServer/blob/main/tests/Shmuelie.WinRTServer.Sample.Server/RemoteThing.cs does

**Comment by hez2010** [comment]
Still no luck even with a `GuidAttribute` added to the `TestClass`.
And note that if I downgrade the server project to net7.0-windows10.0.22621.0, it will fail at `Specified cast is not valid` at `unkwnPtr.CopyTo(instance)` again as the top-most post of this issue.

**Comment by shmuelie** [comment]
The `ITestCase` needs to use the `Windows.Foundation.Metadata.GuidAttribute` attribute, not the `System.Runtime.InteropServices.GuidAttribute` attribute.

**Comment by hez2010** [comment]
Still not working even with `Windows.Foundation.Metadata.GuidAttribute`. I'm going to create a new project and see if it works.

**Comment by shmuelie** [comment]
@hez2010 if that doesn't work, could you see if the test projects in the `modern-net` branch work for you?

**Comment by hez2010** [comment]
I changed my client from net8.0 to net481 while kept the server project net8.0 and this time it works as expected.
Seems that it's definitely a CsWinRT issue.

**Comment by shmuelie** [comment]
That is very weird as [Shmuelie.WinRTServer.Sample.WpfNet6Client](https://github.com/shmuelie/Shmuelie.WinRTServer/tree/modern-net/tests/Shmuelie.WinRTServer.Sample.WpfNet6Client) worked for me with the WinRT Activation of a .NET 8 server.

**Comment by hez2010** [comment]
Yeah, it's very weird as your sample also works for me...

Here is the repro: https://github.com/hez2010/WinRTServerRepro
It only works if you change the TFM of `WinRTServer.Client/WinRTServer.Client.csproj` from `net8.0-windows10.0.22621.0` to `net481`.

**Comment by hez2010** [comment]
It turns out to be my fault that I didn't copy the winmd files next to the client exe.
Now it works as expected.

**Comment by shmuelie** [comment]
Nice. I'll try to make some improvements to the documentation first but awesome!

**Comment by shmuelie** [comment]
@hez2010 version 1.2.0 published to nuget!
